apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts-db
spec:
  gateways:
  - "{{ .Release.Namespace }}-gateway.{{ .Release.Namespace }}"
  - mesh
  hosts:
  - "carts-db.{{ .Release.Namespace }}.104.197.144.155.xip.io"
  - carts-db
  http:
  - route:
    - destination:
        host: "carts-db.{{ .Release.Namespace }}.svc.cluster.local"
