#
# Dynatrace Demo CI/CD Pipeline
#

#################################################################
# Global Variables
#################################################################
variables:
  APPLICATION_NAME: carts
  APPLICATION_SHORT_NAME: carts
  kubeconf_file: /tmp/kubeconf
  
stages:
  - deploy-test
  - deploy-hardening
  - deploy-production


#################################################################
# Deploy Stage
#################################################################
deploy-cartsdb-in-test:
  image: docker.io/devth/helm:v2.12.3
  stage: deploy-test
  environment:
    name: carts-test
  variables:
    GIT_STRATEGY: fetch
  script:
    - echo ${kube_config} | base64 -d > ${kubeconf_file}
    - export KUBECONFIG=${kubeconf_file}
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - export KUBECONFIG=$KUBECONFIG
    - sed -i "s/REPLACEME/$(kubectl get cm -n keptn keptn-domain -ojsonpath={.data.app_domain})/g" charts/carts-db/values.yaml
    - helm upgrade
      carts-db-${CI_ENVIRONMENT_SLUG}
      --namespace=${CI_ENVIRONMENT_SLUG}
      --install
      --wait
      ./charts/carts-db/ 

deploy-carts-in-test:
  image: docker.io/devth/helm:v2.12.3
  stage: deploy-test
  environment:
    name: carts-test
  variables:
    GIT_STRATEGY: fetch
  script:
    - echo ${kube_config} | base64 -d > ${kubeconf_file}
    - export KUBECONFIG=${kubeconf_file}
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - export KUBECONFIG=$KUBECONFIG
    - sed -i "s/REPLACEME/$(kubectl get cm -n keptn keptn-domain -ojsonpath={.data.app_domain})/g" charts/carts/values.yaml
    - helm upgrade
      carts-${CI_ENVIRONMENT_SLUG}
      --namespace=${CI_ENVIRONMENT_SLUG}
      --install
      --wait
      --force
      ./charts/carts/

dt_test_deployment_event:
  stage: deploy-test
  image: docker.io/mvilliger/keptn-k8s-runner:0.6.2
  environment:
    name: carts-test
  variables:
      GIT_STRATEGY: none
  script: |
    echo ${kube_config} | base64 -d > ${kubeconf_file}
    export KUBECONFIG=${kubeconf_file}
    echo ${kube_config} | base64 -d > ${KUBECONFIG}
    export KUBECONFIG=$KUBECONFIG
    DT_TENANT_URL=$(kubectl -n keptn get secret dynatrace-credentials-gitlab -ojsonpath={.data.dynatrace-credentials} | base64 -d | yq r - -d '*' DT_TENANT | cut -c 3-)
    DT_API_TOKEN=$(kubectl -n keptn get secret dynatrace-credentials-gitlab -ojsonpath={.data.dynatrace-credentials} | base64 -d | yq r - -d '*' DT_API_TOKEN | cut -c 3-)
    echo ${APPLICATION_SHORT_NAME}-${CI_ENVIRONMENT_NAME}
    echo ${CI_COMMIT_SHORT_SHA}
    export DT_PAYLOAD="
    {
      \"eventType\": \"CUSTOM_DEPLOYMENT\",
      \"attachRules\": {
        \"tagRule\" : {
            \"meTypes\" : \"SERVICE\",
            \"tags\" : [ 
              {
                \"context\": \"CONTEXTLESS\",
                \"key\": \"hotday-tag-rule\", 
                \"value\": \"${APPLICATION_SHORT_NAME}-${CI_ENVIRONMENT_NAME}\"
              }
            ]
        }
      },
      \"deploymentName\":\"${CI_COMMIT_MESSAGE}\",
      \"deploymentVersion\":\"${CI_COMMIT_SHORT_SHA}\",
      \"deploymentProject\":\"${CI_PROJECT_ID}\",
      \"ciBackLink\":\"${CI_PIPELINE_URL}\",
      \"source\":\"GitLab\",
      \"customProperties\":{
        \"CI_JOB_URL\": \"${CI_JOB_URL}\",
        \"CI_JOB_ID\": \"${CI_JOB_ID}\",
        \"CI_PROJECT_ID\": \"${CI_PROJECT_ID}\",
        \"Commit\": \"${GIT_COMMIT}\"
      }
    }
    "
    echo $DT_PAYLOAD > payload.tmp
    curl -L -H "Authorization: Api-Token ${DT_API_TOKEN}" -H "Content-Type: application/json" "https://${DT_TENANT_URL}/api/v1/events" -d @payload.tmp
      
deploy-cartsdb-in-hardening:
  image: docker.io/devth/helm:v2.12.3
  stage: deploy-hardening
  environment:
    name: carts-hardening
  variables:
    GIT_STRATEGY: fetch
  script:
    - echo ${kube_config} | base64 -d > ${kubeconf_file}
    - export KUBECONFIG=${kubeconf_file}
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - export KUBECONFIG=$KUBECONFIG
    - sed -i "s/REPLACEME/$(kubectl get cm -n keptn keptn-domain -ojsonpath={.data.app_domain})/g" charts/carts-db/values.yaml
    - helm upgrade
      carts-db-${CI_ENVIRONMENT_SLUG}
      --namespace=${CI_ENVIRONMENT_SLUG}
      --install
      --wait
      ./charts/carts-db/

deploy-carts-in-staging:
  image: docker.io/devth/helm:v2.12.3
  stage: deploy-hardening
  environment:
    name: carts-hardening
  variables:
    GIT_STRATEGY: fetch
  script:
    - echo ${kube_config} | base64 -d > ${kubeconf_file}
    - export KUBECONFIG=${kubeconf_file}
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - export KUBECONFIG=$KUBECONFIG
    - sed -i "s/REPLACEME/$(kubectl get cm -n keptn keptn-domain -ojsonpath={.data.app_domain})/g" charts/carts/values.yaml
    - helm upgrade
      carts-${CI_ENVIRONMENT_SLUG}
      --namespace=${CI_ENVIRONMENT_SLUG}
      --install
      --wait
      --force
      ./charts/carts/

dt_stage_deployment_event:
    stage: deploy-hardening
    image: docker.io/mvilliger/keptn-k8s-runner:0.6.2
    environment:
      name: carts-hardening    
    variables:
        GIT_STRATEGY: none
    script: |
      echo ${kube_config} | base64 -d > ${kubeconf_file}
      export KUBECONFIG=${kubeconf_file}
      echo ${kube_config} | base64 -d > ${KUBECONFIG}
      export KUBECONFIG=$KUBECONFIG    
      DT_TENANT_URL=$(kubectl -n keptn get secret dynatrace-credentials-gitlab -ojsonpath={.data.dynatrace-credentials} | base64 -d | yq r - -d '*' DT_TENANT | cut -c 3-)
      DT_API_TOKEN=$(kubectl -n keptn get secret dynatrace-credentials-gitlab -ojsonpath={.data.dynatrace-credentials} | base64 -d | yq r - -d '*' DT_API_TOKEN | cut -c 3-)
      echo ${APPLICATION_SHORT_NAME}-${CI_ENVIRONMENT_NAME}
      echo ${CI_COMMIT_SHORT_SHA}
      export DT_PAYLOAD="
      {
        \"eventType\": \"CUSTOM_DEPLOYMENT\",
        \"attachRules\": {
          \"tagRule\" : {
              \"meTypes\" : \"SERVICE\",
              \"tags\" : [ 
                {
                  \"context\": \"CONTEXTLESS\",
                  \"key\": \"hotday-tag-rule\", 
                  \"value\": \"${APPLICATION_SHORT_NAME}-${CI_ENVIRONMENT_NAME}\"
                }
              ]
          }
        },
        \"deploymentName\":\"${CI_COMMIT_MESSAGE}\",
        \"deploymentVersion\":\"${CI_COMMIT_SHORT_SHA}\",
        \"deploymentProject\":\"${CI_PROJECT_ID}\",
        \"ciBackLink\":\"${CI_PIPELINE_URL}\",
        \"source\":\"GitLab\",
        \"customProperties\":{
          \"CI_JOB_URL\": \"${CI_JOB_URL}\",
          \"CI_JOB_ID\": \"${CI_JOB_ID}\",
          \"CI_PROJECT_ID\": \"${CI_PROJECT_ID}\",
          \"Commit\": \"${GIT_COMMIT}\"
        }
      }
      "
      echo $DT_PAYLOAD > payload.tmp
      curl -L -H "Authorization: Api-Token ${DT_API_TOKEN}" -H "Content-Type: application/json" "https://${DT_TENANT_URL}/api/v1/events" -d @payload.tmp
  
deploy-cartsdb-in-production:
  image: docker.io/devth/helm:v2.12.3
  stage: deploy-production
  environment:
    name: carts-production
  variables:
    GIT_STRATEGY: fetch
  script:
    - echo ${kube_config} | base64 -d > ${kubeconf_file}
    - export KUBECONFIG=${kubeconf_file}
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - export KUBECONFIG=$KUBECONFIG
    - sed -i "s/REPLACEME/$(kubectl get cm -n keptn keptn-domain -ojsonpath={.data.app_domain})/g" charts/carts-db/values.yaml
    - helm upgrade
      carts-db-${CI_ENVIRONMENT_SLUG}
      --namespace=${CI_ENVIRONMENT_SLUG}
      --install
      --wait
      ./charts/carts-db/

deploy-carts-in-production:
  image: docker.io/devth/helm:v2.12.3
  stage: deploy-production
  environment:
    name: carts-production
  variables:
    GIT_STRATEGY: fetch
  script:
    - echo ${kube_config} | base64 -d > ${kubeconf_file}
    - export KUBECONFIG=${kubeconf_file}
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - export KUBECONFIG=$KUBECONFIG
    - sed -i "s/REPLACEME/$(kubectl get cm -n keptn keptn-domain -ojsonpath={.data.app_domain})/g" charts/carts/values.yaml
    - helm upgrade
      carts-${CI_ENVIRONMENT_SLUG}
      --namespace=${CI_ENVIRONMENT_SLUG}
      --install
      --wait
      --force
      ./charts/carts/

dt_production_deployment_event:
  stage: deploy-production
  image: docker.io/mvilliger/keptn-k8s-runner:0.6.2
  environment:
    name: carts-production    
  variables:
      GIT_STRATEGY: none
  script: |
    echo ${kube_config} | base64 -d > ${kubeconf_file}
    export KUBECONFIG=${kubeconf_file}
    echo ${kube_config} | base64 -d > ${KUBECONFIG}
    export KUBECONFIG=$KUBECONFIG    
    DT_TENANT_URL=$(kubectl -n keptn get secret dynatrace-credentials-gitlab -ojsonpath={.data.dynatrace-credentials} | base64 -d | yq r - -d '*' DT_TENANT | cut -c 3-)
    DT_API_TOKEN=$(kubectl -n keptn get secret dynatrace-credentials-gitlab -ojsonpath={.data.dynatrace-credentials} | base64 -d | yq r - -d '*' DT_API_TOKEN | cut -c 3-)
    echo ${APPLICATION_SHORT_NAME}-${CI_ENVIRONMENT_NAME}
    echo ${CI_COMMIT_SHORT_SHA}
    export DT_PAYLOAD="
    {
      \"eventType\": \"CUSTOM_DEPLOYMENT\",
      \"attachRules\": {
        \"tagRule\" : {
            \"meTypes\" : \"SERVICE\",
            \"tags\" : [ 
              {
                \"context\": \"CONTEXTLESS\",
                \"key\": \"hotday-tag-rule\", 
                \"value\": \"${APPLICATION_SHORT_NAME}-${CI_ENVIRONMENT_NAME}\"
              }
            ]
        }
      },
      \"deploymentName\":\"${CI_COMMIT_MESSAGE}\",
      \"deploymentVersion\":\"${CI_COMMIT_SHORT_SHA}\",
      \"deploymentProject\":\"${CI_PROJECT_ID}\",
      \"ciBackLink\":\"${CI_PIPELINE_URL}\",
      \"source\":\"GitLab\",
      \"customProperties\":{
        \"CI_JOB_URL\": \"${CI_JOB_URL}\",
        \"CI_JOB_ID\": \"${CI_JOB_ID}\",
        \"CI_PROJECT_ID\": \"${CI_PROJECT_ID}\",
        \"Commit\": \"${GIT_COMMIT}\"
      }
    }
    "
    echo $DT_PAYLOAD > payload.tmp
    curl -L -H "Authorization: Api-Token ${DT_API_TOKEN}" -H "Content-Type: application/json" "https://${DT_TENANT_URL}/api/v1/events" -d @payload.tmp
      