#
# Dynatrace Demo CI/CD Pipeline
#

#################################################################
# Global Variables
#################################################################
variables:
  APPLICATION_NAME: carts
  APPLICATION_SHORT_NAME: carts
  kubeconf_file: /tmp/kubeconf
  
stages:
  - test



#################################################################
# Deploy Stage
#################################################################
deploy-cartsdb-in-test:
  image: docker.io/mvilliger/keptn-k8s-runner:0.6.3
  stage: test
  environment:
    name: carts-test
  variables:
    GIT_STRATEGY: fetch
  script:
    - cat $kube_config | base64 -di > ${kubeconf_file}
    - export KUBECONFIG=${kubeconf_file}
    - echo ${kube_config} | base64 -di > ${KUBECONFIG}
    - export KUBECONFIG=$KUBECONFIG
    - kubectl cluster-info
