#
# Dynatrace Demo CI/CD Pipeline
#

#################################################################
# Global Variables
#################################################################
variables:
  APPLICATION_NAME: carts
  APPLICATION_SHORT_NAME: carts
  kubeconf_file: /tmp/kubeconf

stages:
  - deploy-test
  - deploy-hardening
  - deploy-production
  #- verify  


#################################################################
# Deploy Stage
#################################################################

deploy-in-test:
  image: registry.gitlab.com/checkelmann/cicd-tools:latest
  stage: deploy-test
  environment:
    name: carts-test
  variables:
    GIT_STRATEGY: fetch
  # script: |
  #   helm upgrade --install --namespace=${CI_ENVIRONMENT_SLUG} ${APPLICATION_SHORT_NAME} ./charts/carts/
  #   helm upgrade dev-carts --namespace dev --install --wait --force ./carts/
  script:
    - echo ${kube_config} | base64 -d > ${kubeconf_file}
    - export KUBECONFIG=${kubeconf_file}
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - export KUBECONFIG=$KUBECONFIG
    - helm upgrade
      carts-${CI_ENVIRONMENT_SLUG}
      --namespace=${CI_ENVIRONMENT_SLUG}
      --install
      --wait
      --force
      ./charts/carts/  

deploy-in-staging:
  image: registry.gitlab.com/checkelmann/cicd-tools:latest
  stage: deploy-hardening
  environment:
    name: carts-hardening
  variables:
    GIT_STRATEGY: fetch
  script:
    - echo ${kube_config} | base64 -d > ${kubeconf_file}
    - export KUBECONFIG=${kubeconf_file}
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - export KUBECONFIG=$KUBECONFIG
    - helm upgrade
      carts-${CI_ENVIRONMENT_SLUG}
      --namespace=${CI_ENVIRONMENT_SLUG}
      --install
      --wait
      --force
      ./charts/carts/  

deploy-in-production:
  image: registry.gitlab.com/checkelmann/cicd-tools:latest
  stage: deploy-production
  environment:
    name: carts-production
  variables:
    GIT_STRATEGY: fetch
  script:
    - echo ${kube_config} | base64 -d > ${kubeconf_file}
    - export KUBECONFIG=${kubeconf_file}
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - export KUBECONFIG=$KUBECONFIG
    - helm upgrade
      carts-${CI_ENVIRONMENT_SLUG}
      --namespace=${CI_ENVIRONMENT_SLUG}
      --install
      --wait
      --force
      ./charts/carts/  